title:            Jordi Pont-Tuset's site
description:      Welcome to my site.
url:              https://ars-ashuha.ru

owner:
  name:           Ars
  avatar:         avatar_v2.png
  bio:            123
  email:          ars.ashuha@gmail.com
  linkedin: ars-ashuha
  github: ars-ashuha

# google_analytics: UA-52736040-1
# google_verify: https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here

links:
  - title: Curriculum
    url: /resume/ashuha-resume.pdf
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/

timezone:    Europe/Zurich
future:      true
pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
